# Generated by Django 4.1.1 on 2022-10-25 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_categorymodel_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='images/product')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.categorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('main_view', models.FileField(blank=True, null=True, upload_to='images/product_variant')),
                ('side_view', models.FileField(blank=True, null=True, upload_to='images/product_variant')),
                ('top_view', models.FileField(blank=True, null=True, upload_to='images/product_variant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productmodel')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productsizemodel')),
            ],
        ),
    ]
