# Generated by Django 4.1.1 on 2022-10-25 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productmodel_productsizemodel_productvariantmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='catalog.productmodel'),
        ),
    ]
