# Generated by Django 4.1.1 on 2022-10-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_productvariantmodel_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsizemodel',
            name='keys',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
