# Generated by Django 4.1.1 on 2022-10-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productsizemodel_keys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsizemodel',
            name='keys',
        ),
        migrations.AddField(
            model_name='productvariantmodel',
            name='keys',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
