# Generated by Django 4.0.3 on 2022-10-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_productsizemodel_keys_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='keys',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
