# Generated by Django 4.0.3 on 2022-10-31 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_productsizemodel_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsizemodel',
            name='size',
            field=models.CharField(default='hi', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.productsizemodel'),
        ),
    ]
