# Generated by Django 4.1.1 on 2022-10-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0003_alter_sitesetupmodel_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteHeroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('banner', models.FileField(upload_to='images/hero')),
            ],
        ),
    ]
