# Generated by Django 4.1.1 on 2022-10-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_siteheromodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteheromodel',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='ACTIVE', max_length=20),
            preserve_default=False,
        ),
    ]
