# Generated by Django 4.1.1 on 2022-10-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0005_siteheromodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteheromodel',
            name='banner',
        ),
        migrations.AddField(
            model_name='siteheromodel',
            name='image',
            field=models.FileField(default='lll', upload_to='images/hero'),
            preserve_default=False,
        ),
    ]
