# Generated by Django 4.1.1 on 2022-10-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
