# Generated by Django 4.1.1 on 2022-10-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_ordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='price',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='quantity',
            field=models.JSONField(null=True),
        ),
    ]
