# Generated by Django 4.1.1 on 2022-10-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_checkoutmodel_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutmodel',
            name='grand_total',
            field=models.FloatField(default=120000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkoutmodel',
            name='transportation',
            field=models.FloatField(default=20000),
            preserve_default=False,
        ),
    ]
